default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docker_compose_rails_dev

test:
  <<: *default
  database: docker_compose_rails_test

production:
  <<: *default
  database: docker_compose_rails_prod
